config/routes.rb
Rails.application.routes.draw do
  resources :temperatures
  root 'temperatures#index'

  get 'welcome/index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/temperature.rb
class Temperature < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/temperatures_controller.rb
class TemperaturesController < ApplicationController
  before_action :set_temperature, only: [:show, :edit, :update, :destroy]

  # GET /temperatures
  # GET /temperatures.json
  def index
    @temperatures = Temperature.all
  end

  # GET /temperatures/1
  # GET /temperatures/1.json
  def show
  end

  # GET /temperatures/new
  def new
    @temperature = Temperature.new
  end

  # GET /temperatures/1/edit
  def edit
  end

  # POST /temperatures
  # POST /temperatures.json
  def create
    @temperature = Temperature.new(temperature_params)

    respond_to do |format|
      if @temperature.save
        format.html { redirect_to action: "index", notice: 'Temperature was successfully created.' }
        format.json { render :show, status: :created, location: @temperature }
      else
        format.html { render :new }
        format.json { render json: @temperature.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /temperatures/1
  # PATCH/PUT /temperatures/1.json
  def update
    respond_to do |format|
      if @temperature.update(temperature_params)
        format.html { redirect_to @temperature, notice: 'Temperature was successfully updated.' }
        format.json { render :show, status: :ok, location: @temperature }
      else
        format.html { render :edit }
        format.json { render json: @temperature.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /temperatures/1
  # DELETE /temperatures/1.json
  def destroy
    @temperature.destroy
    respond_to do |format|
      format.html { redirect_to temperatures_url, notice: 'Temperature was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_temperature
      @temperature = Temperature.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def temperature_params
      params.require(:temperature).permit(:daily_avg_temp)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    temp_arr = []
    Temperature.all.each do |temp|
      temp_arr.push(temp.daily_avg_temp)
    end

    @data = temp_arr
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/temperatures_helper.rb
module TemperaturesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>D3Test</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/temperatures/_form.html.erb
<%= form_with(model: temperature, local: true) do |form| %>
  <% if temperature.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(temperature.errors.count, "error") %> prohibited this temperature from being saved:</h2>

      <ul>
      <% temperature.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :daily_avg_temp %>
    <%= form.text_field :daily_avg_temp, id: :temperature_daily_avg_temp, :autofocus=>true %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/temperatures/edit.html.erb
<h1>Editing Temperature</h1>

<%= render 'form', temperature: @temperature %>

<%= link_to 'Show', @temperature %> |
<%= link_to 'Back', temperatures_path %>

app/views/temperatures/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Temperatures</h1>

<table>
  <thead>
    <tr>
      <th>Daily avg temp</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @temperatures.each do |temperature| %>
      <tr>
        <td><%= temperature.daily_avg_temp %></td>
        <td><%= link_to 'Show', temperature %></td>
        <td><%= link_to 'Edit', edit_temperature_path(temperature) %></td>
        <td><%= link_to 'Destroy', temperature, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Temperature', new_temperature_path %>

app/views/temperatures/new.html.erb
<h1>New Temperature</h1>

<%= render 'form', temperature: @temperature %>

<%= link_to 'Back', temperatures_path %>

app/views/temperatures/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Daily avg temp:</strong>
  <%= @temperature.daily_avg_temp %>
</p>

<%= link_to 'Edit', edit_temperature_path(@temperature) %> |
<%= link_to 'Back', temperatures_path %>

app/views/welcome/index.html.erb
<!DOCTYPE html>
<meta charset="utf-8">
<style>

.chart div {
  font: 10px sans-serif;
  background-color: steelblue;
  text-align: right;
  padding: 3px;
  margin: 1px;
  color: white;
}

</style>
<div class="chart"></div>


<script src="//d3js.org/d3.v3.min.js"></script>


<script>

var data = <%= @data %>;

var x = d3.scale.linear()
    .domain([0, d3.max(data)])
    .range([0, 420]);

d3.select(".chart")
  .selectAll("div")
    .data(data)
  .enter().append("div")
    .style("width", function(d) { return x(d) + "px"; })
    .text(function(d) { return d; });

</script>